// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpBZP7w43NAZPrw-fO6huv_U50d4_5TAM',
    appId: '1:130189881033:android:a96ca0402605d4cb06a718',
    messagingSenderId: '130189881033',
    projectId: 'piet-bus-connect',
    storageBucket: 'piet-bus-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCwpq3Vby_HXcL0xEy7X0ly6B993wuB3I',
    appId: '1:130189881033:ios:4c45762bfaa8aa7106a718',
    messagingSenderId: '130189881033',
    projectId: 'piet-bus-connect',
    storageBucket: 'piet-bus-connect.appspot.com',
    androidClientId: '130189881033-ih84vs6p7oi8v2hqenvbnqq6g7kurfa7.apps.googleusercontent.com',
    iosClientId: '130189881033-qja0oh1ke39dl1obi7b99m7na6tv99ch.apps.googleusercontent.com',
    iosBundleId: 'in.co.piet.busconnect',
  );
}
